/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BudgetImport } from './routes/budget'
import { Route as AccountsImport } from './routes/accounts'
import { Route as AccountsIndexImport } from './routes/accounts.index'
import { Route as AccountsIdImport } from './routes/accounts.$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const BudgetRoute = BudgetImport.update({
  path: '/budget',
  getParentRoute: () => rootRoute,
} as any)

const AccountsRoute = AccountsImport.update({
  path: '/accounts',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AccountsIndexRoute = AccountsIndexImport.update({
  path: '/',
  getParentRoute: () => AccountsRoute,
} as any)

const AccountsIdRoute = AccountsIdImport.update({
  path: '/$id',
  getParentRoute: () => AccountsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsImport
      parentRoute: typeof rootRoute
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetImport
      parentRoute: typeof rootRoute
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdImport
      parentRoute: typeof AccountsImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexImport
      parentRoute: typeof AccountsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AccountsRoute: AccountsRoute.addChildren({
    AccountsIdRoute,
    AccountsIndexRoute,
  }),
  BudgetRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/accounts",
        "/budget"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/accounts": {
      "filePath": "accounts.tsx",
      "children": [
        "/accounts/$id",
        "/accounts/"
      ]
    },
    "/budget": {
      "filePath": "budget.tsx"
    },
    "/accounts/$id": {
      "filePath": "accounts.$id.tsx",
      "parent": "/accounts"
    },
    "/accounts/": {
      "filePath": "accounts.index.tsx",
      "parent": "/accounts"
    }
  }
}
ROUTE_MANIFEST_END */
