/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BudgetImport } from './routes/budget'
import { Route as AccountIdImport } from './routes/account.$id'

// Create Virtual Routes

const AccountsLazyImport = createFileRoute('/accounts')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AccountsLazyRoute = AccountsLazyImport.update({
  path: '/accounts',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/accounts.lazy').then((d) => d.Route))

const BudgetRoute = BudgetImport.update({
  path: '/budget',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AccountIdRoute = AccountIdImport.update({
  path: '/account/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetImport
      parentRoute: typeof rootRoute
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsLazyImport
      parentRoute: typeof rootRoute
    }
    '/account/$id': {
      id: '/account/$id'
      path: '/account/$id'
      fullPath: '/account/$id'
      preLoaderRoute: typeof AccountIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  BudgetRoute,
  AccountsLazyRoute,
  AccountIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/budget",
        "/accounts",
        "/account/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/budget": {
      "filePath": "budget.tsx"
    },
    "/accounts": {
      "filePath": "accounts.lazy.tsx"
    },
    "/account/$id": {
      "filePath": "account.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
